version: "3.7"

networks:
  redis-network:
    driver: bridge

services:
  redis-master:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=abcdef
    networks:
      - redis-network
    ports:
      - 6379:6379
    container_name: redis-master

  redis-slave-1:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=abcdef
      - REDIS_PASSWORD=abcdef
    networks:
      - redis-network
    ports:
      - 6479:6379
    depends_on:
      - redis-master
    container_name: redis-slave-1

  redis-slave-2:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=abcdef
      - REDIS_PASSWORD=abcdef
    networks:
      - redis-network
    ports:
      - 6579:6379
    depends_on:
      - redis-master
    container_name: redis-slave-2

  redis-slave-3:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=abcdef
      - REDIS_PASSWORD=abcdef
    networks:
      - redis-network
    ports:
      - 6679:6379
    depends_on:
      - redis-master
    container_name: redis-slave-3

  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000 # 센티넬이 마스터노드의 장애여부를 판단하는 시간
      - REDIS_MASTER_HOST=redis-master # master 노드의 호스트
      - REDIS_MASTER_PORT_NUMBER=6379 # master 노드의 포트번호
      - REDIS_MASTER_SET=redis-master-set # 모니터링 할 Redis 인스턴스 set의 이름
      - REDIS_MASTER_PASSWORD=abcdef
      - REDIS_SENTINEL_PASSWORD=abcdef
      - REDIS_SENTINEL_QUORUM=2 # master의 장애를 동의하는 센티널의 개수
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3
    ports:
      - '26379-26381:26379'
    networks:
      - redis-network
