version: '3.7'
services:
  redis-master:
    container_name: redis-master
    image: redis
    ports:
      - 6379:6379
  redis-slave-a:
    container_name: redis-slave-a
    image: redis
    ports:
      - 8000:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
  redis-slave-b:
    container_name: redis-slave-b
    image: redis
    ports:
      - 8001:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
