name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
      - uses: actions/checkout@v3
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.1=7
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test
